version: "2"
services:

  dtsf_server:
    image: wangjichao/dtsf_api:latest
    container_name: dtsf_server
    restart: always
    mem_limit: 512m
    working_dir: /home/www-data/dtsf
    hostname: dtsf_server
    ports:
      - "9505:9501"
    volumes_from:
      - apollo_www_data
    command: "php application/index.php"

  apollo_config:
    image: wangjichao/dtsf_api:latest
    container_name: apollo_config
    restart: always
    working_dir: /home/www-data/dtsf
    depends_on:
      - dtsf_server
    mem_limit: 512m
    hostname: apollo_config
    volumes_from:
      - dtsf_server
    command: "./apollo/apollo_client > /tmp/apollo.txt 2>&1"
    environment:
      - CLYTIE_APPID=dtq_api
      - CLYTIE_CLUSTER=default
      - CLYTIE_NAMESPACES=server.yaml mysql.yaml celery.yaml redis.yaml
      - CLYTIE_IP=10.70.120.79:8089
      - CLYTIE_GENERATOR=php
      - CLYTIE_SUFFIX=php
      - CLYTIE_PATH=../application/Config

  apollo_www_data:
    image: alpine:latest
    container_name: apollo_www_data
    volumes:
      - ../../dtsf:/home/www-data/dtsf